<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net48</TargetFrameworks>
    <AssemblyName>Yxlon</AssemblyName>
    <RootNamespace>Virinco.WATS.Converter.Yxlon</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Virinco.WATS.Testing" Version="*" />
    <Compile Remove="ConverterTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Virinco.WATS.Testing" Version="*" />
    <PackageReference Include="Virinco.WATS.ClientAPI" Version="7.*">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Virinco.WATS.StandardConverters" Version="7.*" />
  </ItemGroup>

</Project>

